server:
  port: 8033
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8
    username: root
    password: kusokuso
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: 
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: kusokuso
    timeout: 5000
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        
mybatis:
  type-aliases-package: com.cn.aac.entity
  mapper-locations: ['mapper/*.xml']
  
logging:
  level:
    com:
      cn:
        aac: debug
        